# Basic Information
baseURL = "/"
languageCode = "en-us"
title = "Dan Manners Dot Com"
theme = "hugo-coder"
googleAnalytics = "UA-131029076-1"

# Specific Customization
paginate = 30
canonifyurls = true
pygmentscodefences = true
PygmentsStyle = "monokai"
pygmentscodefencesguesssyntax = true

# After Hugo 0.60, this is necessary to use HTML in markup documents.
[markup.goldmark.renderer]
unsafe = true

# Default parameters on the home/about page.
[params]
    author = "Dan Manners"
    info = "Senior Site Reliability, DevOps, and Network Engineer"
    description = "Built by Hugo"
    keywords = "developer,personal"
    avatarurl = "images/headshot.jpg"
    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"
    footercontent = "Located in Raleigh, NC"
    hidecredits = true
    hidecopyright = false
    rtl = false
    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/danmanners/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/danmanners/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/danielmanners/"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 3
    url = "mailto:daniel.a.manners@gmail.com"
[[params.social]]
    name = "Phone"
    icon = "fa fa-phone fa-2x"
    weight = 3
    url = "tel:9147155428"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Posts"
    weight = 2
    url = "/posts/"
[[menu.main]]
    name = "Resume"
    weight = 2
    url = "https://resume.danmanners.com/"
