# Cross compile the website docker container and push to Docker Hub
name: Cross Compile danmanners-dot-com

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # This is required in order to build ARM images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # This is required in order to cross-compile ARM images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Makes sure to log into Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Should be the equivilant of this command
      # docker buildx build --no-cache --push \
      #   --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v8 \
      #   -t danielmanners/danmanners-dot-com:flux .
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v8
          push: true
          no-cache: true
          tags: |
            danielmanners/danmanners-dot-com:flux
